package com.example.dopamine_gate_mobile

import android.accessibilityservice.AccessibilityService
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.PixelFormat
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.view.Gravity
import android.view.View
import android.view.WindowManager
import android.view.accessibility.AccessibilityEvent
import android.widget.Button
import android.widget.LinearLayout
import android.widget.TextView

class DopamineAccessibilityService : AccessibilityService() {

    companion object {
        private const val TAG = "DopamineGate"

        // Prevent rapid duplicate processing while YouTube is loading.
        private const val DEBOUNCE_MS = 800L

        const val YOUTUBE_PACKAGE = "com.google.android.youtube"
    }

    private val blockedApps: Set<String> = setOf(YOUTUBE_PACKAGE)

    private var windowManager: WindowManager? = null

    private var overlayView: View? = null

    private var isOverlayShowing = false

    private var isLeavingBlockedApp = false

    private var lastTriggerTime = 0L

    private val handler = Handler(Looper.getMainLooper())

    override fun onServiceConnected() {
        super.onServiceConnected()

        windowManager = getSystemService(Context.WINDOW_SERVICE) as? WindowManager

        Log.d(TAG, "Accessibility Service connected")
    }

    override fun onAccessibilityEvent(event: AccessibilityEvent?) {

        if (event?.eventType != AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED) {
            return
        }

        val packageName = event.packageName?.toString() ?: return

        /*
         * Ignore events generated by Dopamine Gate itself.
         */
        if (packageName == applicationContext.packageName) {
            return
        }

        /*
         * If the user has explicitly chosen to leave the blocked app,
         * don't immediately recreate the gate while Android is processing
         * the BACK/Intent actions.
         */
        if (isLeavingBlockedApp) {
            Log.d(TAG, "Leaving blocked app — ignoring event from $packageName")
            return
        }

        /*
         * Once the overlay is visible, keep it visible.
         */
        if (isOverlayShowing) {
            return
        }

        if (!blockedApps.contains(packageName)) {
            return
        }

        val currentTime = System.currentTimeMillis()

        /*
         * Debounce repeated YouTube window events.
         */
        if (currentTime - lastTriggerTime < DEBOUNCE_MS) {
            Log.d(TAG, "Ignoring duplicate blocked-app event: $packageName")
            return
        }

        lastTriggerTime = currentTime

        Log.d(TAG, "BLOCKED APP DETECTED: $packageName")

        showOverlay()
    }

    private fun showOverlay() {

        /*
         * Absolute single-instance protection.
         */
        if (isOverlayShowing || overlayView != null) {
            Log.d(TAG, "Overlay already exists — not creating another")
            return
        }

        val overlayType =
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
                } else {
                    @Suppress("DEPRECATION") WindowManager.LayoutParams.TYPE_PHONE
                }

        val layoutParams =
                WindowManager.LayoutParams(
                                WindowManager.LayoutParams.MATCH_PARENT,
                                WindowManager.LayoutParams.MATCH_PARENT,
                                overlayType,
                                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                                        WindowManager.LayoutParams.FLAG_FULLSCREEN or
                                        WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN or
                                        WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
                                PixelFormat.TRANSLUCENT
                        )
                        .apply { gravity = Gravity.CENTER }

        val container =
                LinearLayout(this).apply {
                    orientation = LinearLayout.VERTICAL

                    gravity = Gravity.CENTER

                    setBackgroundColor(Color.parseColor("#121212"))

                    setPadding(60, 60, 60, 60)

                    isClickable = true
                    isFocusable = false
                }

        val title =
                TextView(this).apply {
                    text = "YouTube is Locked!"

                    textSize = 26f

                    setTextColor(Color.WHITE)

                    gravity = Gravity.CENTER
                }

        val subtitle =
                TextView(this).apply {
                    text = "Take a breath.\n\n" + "Do you really need to open this right now?"

                    textSize = 16f

                    setTextColor(Color.LTGRAY)

                    gravity = Gravity.CENTER

                    setPadding(0, 30, 0, 50)
                }

        val exitButton =
                Button(this).apply {
                    text = "Go to Dopamine Gate"

                    setBackgroundColor(Color.parseColor("#6200EE"))

                    setTextColor(Color.WHITE)

                    setPadding(40, 20, 40, 20)

                    setOnClickListener {

                        if (isLeavingBlockedApp) {
                            return@setOnClickListener
                        }

                        isLeavingBlockedApp = true

                        Log.d(TAG, "User chose Go to Dopamine Gate — Terminating YouTube")

                        // 1. Force YouTube to close its active task
                        performGlobalAction(GLOBAL_ACTION_BACK)
                        Log.d(TAG, "First GLOBAL_ACTION_BACK executed")

                        handler.postDelayed(
                                {
                                    performGlobalAction(GLOBAL_ACTION_BACK)
                                    Log.d(TAG, "Second GLOBAL_ACTION_BACK executed")
                                },
                                100L
                        )

                        // 2. Launch your Flutter app's MainActivity using applicationContext
                        handler.postDelayed(
                                {
                                    val intent = Intent(applicationContext, MainActivity::class.java).apply {
                                        addFlags(
                                            Intent.FLAG_ACTIVITY_NEW_TASK or
                                            Intent.FLAG_ACTIVITY_CLEAR_TOP or
                                            Intent.FLAG_ACTIVITY_SINGLE_TOP or
                                            Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
                                        )
                                    }
                                    applicationContext.startActivity(intent)
                                    Log.d(TAG, "MainActivity launched from isolated process")

                                    // 3. Dismount overlay once MainActivity opens
                                    handler.postDelayed(
                                            {
                                                removeOverlay()

                                                handler.postDelayed(
                                                        {
                                                            isLeavingBlockedApp = false
                                                            Log.d(TAG, "Redirect sequence completed")
                                                        },
                                                        300L
                                                )
                                            },
                                            200L
                                    )
                                },
                                200L
                        )
                    }
                }

        container.addView(title)

        container.addView(subtitle)

        container.addView(exitButton)

        try {

            windowManager?.addView(container, layoutParams)

            overlayView = container

            isOverlayShowing = true

            Log.d(TAG, "Overlay screen drawn successfully")
        } catch (e: Exception) {

            overlayView = null

            isOverlayShowing = false

            Log.e(TAG, "Failed to draw overlay window", e)
        }
    }

    private fun removeOverlay() {

        val view = overlayView ?: return

        try {

            windowManager?.removeView(view)

            Log.d(TAG, "Overlay removed successfully")
        } catch (e: Exception) {

            Log.e(TAG, "Failed to remove overlay window", e)
        } finally {

            overlayView = null

            isOverlayShowing = false
        }
    }

    override fun onInterrupt() {

        Log.d(TAG, "Accessibility service interrupted")

        removeOverlay()
    }

    override fun onDestroy() {

        Log.d(TAG, "Accessibility service destroyed")

        handler.removeCallbacksAndMessages(null)

        removeOverlay()

        super.onDestroy()
    }
}